name: Build

on:
  push:
  pull_request:
  release:    
    types: [published,edited]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Get the sources
        uses: actions/checkout@v4

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Install .NET Core SDKs
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            10.0.x

      - name: Run Cake build
        if: github.event_name == 'pull_request'
        run: dotnet run build.cs -- --verbosity=Verbose --target=Default
        env:
          sonarLogin: ${{ secrets.SONARLOGIN }}
          nugetApiKey: ${{ secrets.NUGETAPIKEY }}

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: github.event_name != 'pull_request'
        run: >
          dotnet run build.cs --
          --verbosity=Verbose
          --target=Docker-Push
          --github-owner "${{ github.repository_owner }}"
          --github-image-name "${{ github.event.repository.name }}"
          --push-latest=${{ github.event_name == 'release' || github.ref_name == github.event.repository.default_branch }}
